services:
  database:
    image: postgres:17
    container_name: eshop_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - eshop_data:/var/lib/postgresql/data

volumes:
  eshop_data: